version: '3.9'

services:

  # PHP Service
  php-fpm:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    #tty: true
    #working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb

  # Nginx Service
  webserver:
    #image: nginx:alpine
    image: nginx
    restart: always
    tty: true
    ports:
      - '${APP_PORT}:80'
      - '${MIX_API_PORT}:81'
    volumes:
      - ./:/var/www/html
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - frontend
      - backend

  # API Service
  api:
    restart: always
    build: .
    tty: true
    # ports:
    #   - '${MIX_API_PORT}:80'
    depends_on:
      - webserver
    volumes:
      - ./:/var/www/html

  # Frontend Serivce
  frontend:
    restart: always
    build: ./frontend
    command: "npm run dev"
    # tty: true
    # ports:
    #   - '${MIX_FRONTEND_PORT}:8881'

  # Backend Service
  backend:
    restart: always
    build: ./backend
    command: "npm run dev"
    # tty: true
    # ports:
    #   - '${MIX_BACKEND_PORT}:8882'

  # Mariadb Service
  mariadb:
    image: 'mariadb:10'
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/db:/var/lib/mysql/

  # Phpmyadmin Service
  adminer:
    image: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - '${ADMINER_PORT}:80'
    environment:
      PMA_HOST: mariadb


